(ns aoc2015.day25)

"To continue, please consult the code grid in the manual.  
 Enter the code at row 2947, column 3029."

"Day 25: Let It Snow
 
 code generation algorithm
 codes are printed on an infinite sheet of paper

   | 1   2   3   4   5   6  
---+---+---+---+---+---+---+
 1 |  1   3   6  10  15  21
 2 |  2   5   9  14  20
 3 |  4   8  13  19
 4 |  7  12  18
 5 | 11  17
 6 | 16

 The first code is 20151125

  After that, each code is generated by taking the previous one, 
 multiplying it by 252533, and then 
 keeping the remainder from dividing that value by 33554393
 "

(defn next-code [old-code]
  (mod (* old-code 252533) 33554393))

(next-code 20151125)

(* 2947 3029)
;; => 8926463

(take 11 (iterate next-code 20151125))

"n: r,c 
 0: 1,1
 1: 2,1
 2: 1,2
 3: 3,1
 4: 2,2
 5: 1,3
 6: 4,1
 7: 3,2
 8: 2,3
 9, 1,4
 10: 5,1
 11: 4,2
 12: 3,3
 13: 2,4
 14: 1,5

 x: 2947, 3029
 "

(defn tri-row)